[package]
name = "ghex"
version = "0.1.0"
authors = ["Uchio Kondo <udzura@udzura.jp>"]
edition = "2018"

[dependencies]
chrono = { version = "^0.4", features = ["serde"] }
anyhow = "1.0"
graphql_client = "0.9"
serde = "^1.0"
reqwest = { version = "^0.10", features = ["json", "blocking"] }
prettytable-rs = "^0.7"
structopt = "^0.3"
envy = "^0.3"
log = "^0.4"
env_logger = "^0.8"
